services:
  app1:
    image: devops-app:latest
    container_name: app1
    environment:
      - INSTANCE_NAME=app1

  app2:
    image: devops-app:latest
    container_name: app2
    environment:
      - INSTANCE_NAME=app2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
